### ISSUE TITLE
What's the backstory to custom-selectors-missing-colon?

### ISSUE THREAD

**Issue by jedmao** [cssnext/postcss-cssnext#3]
See https://github.com/cssnext/cssnext/blob/master/src/fixes/custom-selectors-missing-colon.js

Why were these fixes not implemented in the [custom-selectors](https://github.com/postcss/postcss-custom-selectors) plugin itself?

**Comment by MoOx** [comment]
Explanation here https://github.com/cssnext/cssnext/blob/master/CHANGELOG.md#170---2015-06-17
tell me if that's enough.
the plugin was handling it, but since it was incorrect, the plugin removed the support in a major release, so instead of having to make a major release as well for cssnext, I added this fix + warning so people might have a better ux and can easily upgrade + update their codebase.

We can probably skip this here :) (with a note in the changelog maybe).

**Comment by jedmao** [comment]
I see! So we don't have to worry about this then, because we can start off version 1.0 without supporting the incorrect syntax in the first place.

**Comment by MoOx** [comment]
Correct.
But [maybe 2.0](https://github.com/cssnext/postcss-cssnext/issues/4) ;)
